easy_admin:
    #Personalización:
    site_name: '<img src="/images/logo-grey.png" alt="logo de Expertosit" title="Logo de Expertosit" height="20" width="163">'

    design:
        brand_color: '#97b830'

    list:
        actions:
            - { name: 'show', label: '', icon: 'search' }
            - { name: 'edit', label: '', icon: 'edit' }
            - { name: 'delete', label: '', icon: 'trash' }