#Personalización:
easy_admin:
    site_name: '<img src="/images/logo-grey.png" alt="logo de Expertosit" title="Logo de Expertosit" height="20" width="163">'

    design:
        brand_color: '#97b830'
        assets:
            css:
                - '/bundles/easyadmin/stylesheet/custom.css'
        form_theme: 'vertical'
        menu:
        - label: 'Tienda'
          icon: 'shopping-cart'
          children:
            - { label: 'Reparaciones', entity: 'Repair', icon: 'cog', default: true }
            - { label: 'Ventas', entity: 'Sale', icon: 'shopping-cart' }
            - { label: 'Añadir'}
            - { label: 'Reparación', entity: 'Repair', icon: 'plus-circle', params: { action: 'new' } }
            - { label: 'Venta', entity: 'Sale', icon: 'plus-circle', params: { action: 'new' } }

        - label: 'Personal'
          icon: 'users'
          children:
            - { label: 'Empleados', entity: 'Employee', icon: 'user' }
            - { label: 'Clientes', entity: 'Client', icon: 'user' }
            - { label: 'Añadir' }
            - { label: 'Empleado', entity: 'Employee', icon: 'plus-circle', params: { action: 'new' } }
            - { label: 'Cliente', entity: 'Client', icon: 'plus-circle', params: { action: 'new' } }

        - label: 'Smartphones'
          icon: 'tablet'
          children:
            - { label: 'Dispositivos', entity: 'Device', icon: 'mobile' }
#            - { label: 'IMEI', entity: 'Imei', icon: 'barcode' }
            - { label: 'Añadir' }
            - { label: 'Dispositivo', entity: 'Device', icon: 'plus-circle', params: { action: 'new' } }
#            - { label: 'IMEI', entity: 'Imei', icon: 'plus-circle', params: { action: 'new' } }

        - label: 'Estados'
          icon: 'tachometer'
          entity: 'State'

    formats:
        datetime: 'd/m/Y'

    list:
        actions:
            - { name: 'show', label: '', icon: 'search' }
            - { name: 'edit', label: '', icon: 'edit' }
            - { name: 'delete', label: '', icon: 'trash' }