#Personalización:
easy_admin:
    site_name: '<img src="/images/logo-grey.png" alt="logo de Expertosit" title="Logo de Expertosit" height="20" width="163">'

    design:
        brand_color: '#97b830'
        assets:
            css:
                - '/bundles/easyadmin/stylesheet/custom.css'
        menu:
            - label: 'Products'
              icon: 'archive' # book
              children:
                   - { entity: 'Repair', icon: 'wrench', params: { sortField: 'starDate' }, default: true }
                   - { entity: 'Sale', icon: 'credit-card' }
            - label: 'Users'
              icon: 'users'
              children:
                  - { entity: 'Employee', icon: 'user' }
                  - { entity: 'Client', icon: 'user' }
            - label: 'Devices'
              icon: 'tablet'
              children:
                  - { entity: 'Device', icon: 'mobile' }
                  - { entity: 'Imei', icon: 'asterisk' }
            - label: 'Others'
              icon: 'asterisk'
              children:
                  - { entity: 'State', icon: 'asterisk' }

    formats:
        datetime: 'd/m/Y'

    list:
        actions:
            - { name: 'show', label: '', icon: 'search' }
            - { name: 'edit', label: '', icon: 'edit' }
            - { name: 'delete', label: '', icon: 'trash' }