#Personalización:
easy_admin:
    site_name: '<img src="/images/logo-grey.png" alt="logo de Expertosit" title="Logo de Expertosit" height="20" width="163">'

    design:
        brand_color: '#97b830'
        assets:
            css:
                - '/bundles/easyadmin/stylesheet/custom.css'
        form_theme: 'vertical'
        menu:
        - label: 'Facturas'
          icon: 'folder'
          children:
            - { label: 'Recibos', entity: 'Receipt', icon: 'folder-open', default: true }
            - { label: 'Facturas', entity: 'Invoice', icon: 'folder-open' }
            - { label: 'Añadir'}
            - { label: 'Recibo', entity: 'Receipt', icon: 'plus-circle', params: { action: 'new' } }
            - { label: 'Factura', entity: 'Invoice', icon: 'plus-circle', params: { action: 'new' } }

        - label: 'Tienda'
          icon: 'shopping-cart'
          children:
            - { label: 'Empleados', entity: 'Employee', icon: 'user' }
            - { label: 'Clientes', entity: 'Client', icon: 'user' }
            - { label: 'Dispositivos', entity: 'Device', icon: 'tablet' }
            - { label: 'Añadir' }
            - { label: 'Empleado', entity: 'Employee', icon: 'plus-circle', params: { action: 'new' } }
            - { label: 'Cliente', entity: 'Client', icon: 'plus-circle', params: { action: 'new' } }
            - { label: 'Dispositivos', entity: 'Device', icon: 'plus-circle', params: { action: 'new' } }

        - label: 'Estados'
          icon: 'tachometer'
          entity: 'State'

    formats:
        datetime: 'd/m/Y'

    list:
        actions:
            - { name: 'show', label: '', icon: 'search' }
            - { name: 'edit', label: '', icon: 'edit' }
            - { name: 'delete', label: '', icon: 'trash' }