# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\Employee:
            algorithm: bcrypt
            cost: 4

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        backend:
            entity:
                class: AppBundle:Employee
                property: username

    firewalls:
        backend:
            anonymous: ~
            provider: backend
            form_login:
                login_path: /admin/login
                check_path: /admin/login_check
            logout:
                path: /admin/logout
                target: /admin/login

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html