easy_admin:
    entities:
        Brand:
            class: AppBundle\Entity\Brand
            list:
                title: 'Marcas'
                sort: [ 'name', 'ASC' ]
                fields: [ { property: 'image', type: 'image', base_path: '%vich_product_images%' }, 'name', 'models' ]
            show:
                fields: [ 'id', { property: 'image', type: 'image', base_path: '%vich_product_images%' }, 'name', 'models' ]
            form:
                fields:
                    - { type: 'group', label: 'Image', icon: 'picture-o', css_class: 'col-sm-6' }
                    - { property: 'imageFile', type: 'vich_image' }

                    - { type: 'group', label: 'Name', icon: 'mobile', css_class: 'col-sm-12' }
                    - { property: 'name' }

