easy_admin:
    entities:
        Client:
            class: AppBundle\Entity\Client
            list:
                title: 'Clientes'
                fields: ['id', 'completeName', 'email', 'address',  { property: 'telephone', type: 'tel' }, 'repairs', { property: 'sales', label: 'Compras' } ]
            show:
                fields: ['id', 'name', 'lastName', 'email', 'address', { property: 'telephone', type: 'tel' }, 'repairs', { property: 'sales', label: 'Compras' } ]
            form:
                fields:
                    - { type: 'group', label: 'Personal Information', icon: 'envelope-o', css_class: 'col-sm-6' }
                    - { property: 'name' }
                    - { property: 'lastName' }
                    - { property: 'email' }
                    - { property: 'telephone' }
                    - { property: 'address' }
