easy_admin:
    entities:
        Device:
            class: AppBundle\Entity\Device
            list:
                title: 'Dispositivos'
                max_results: 10
                fields: [ 'phone', 'color', 'storageSize', 'imeiPrimary', 'imeiSecondary' ]
            show:
                fields: [ 'id', 'phone', 'color', 'storageSize', 'imeiPrimary', 'imeiSecondary', 'repairs', 'sales'  ]
            form:
                fields:
                    - { type: 'group', label: 'Device Information', icon: 'mobile', css_class: 'col-sm-6' }
                    - { property: 'phone' }
                    - { property: 'color' }
                    - { property: 'storageSize' }

                    - { type: 'group', label: 'IMEI', icon: 'barcode', css_class: 'col-sm-6' }
                    - { property: 'imeiPrimary' }
                    - { property: 'imeiSecondary' }
