easy_admin:
    entities:
        Device:
            class: AppBundle\Entity\Device
            list:
                title: 'Dispositivos'
                sort: [ 'brand', 'ASC' ]
                fields: [ { property: 'brand.image', type: 'image', base_path: '%vich_product_images%', label: 'Imagen' }, 'brand', 'model', { property: 'webPage', type: 'url' } ]
            show:
                fields: [ 'id', { property: 'brand.image', type: 'image', base_path: '%vich_product_images%', label: 'Imagen' }, 'brand', 'model', { property: 'webPage', type: 'url' }, 'repairs', 'sales' ]
            form:
                fields:
                    - { type: 'group', label: 'Device Information', icon: 'mobile', css_class: 'col-sm-12' }
                    - { property: 'brand' }
                    - { property: 'model' }

                    - { type: 'group', label: 'Web Page', icon: 'external-link', css_class: 'col-sm-12' }
                    - { property: 'webPage', type: 'url' }
