#easy_admin:
#    entities:
#        Imei:
#            class: AppBundle\Entity\Imei
#            password_encoding: { algorithm: 'bcrypt', cost: 4 }
#            list:
#                title: 'Imei'
#                fields: [ { property: 'sale', label: 'Dispositivo' }, { property: 'code', label: 'IMEI' } ]
#            show:
#                fields: ['id', { property: 'sale', label: 'Dispositivo' }, { property: 'code', label: 'IMEI' } ]
#            form:
#                fields:
#                    - { type: 'group', label: 'IMEI', icon: 'barcode', css_class: 'col-sm-12' }
#                    - { property: 'code', type: 'number' }
#                    - { property: 'sale' }