easy_admin:
    entities:
        Phone:
            class: AppBundle\Entity\Phone
            list:
                title: 'Modelos de Smartphone'
                fields: [ { property: 'brand.image', type: 'image', base_path: '%vich_product_images%', label: 'Imagen' }, 'brand', 'name', { property: 'webPage', type: 'url' } ]
            show:
                fields: [ 'id', { property: 'brand.image', type: 'image', base_path: '%vich_product_images%', label: 'Imagen' }, 'brand', 'name', { property: 'webPage', type: 'url' }, 'devices' ]
            form:
                fields:
                    - { type: 'group', label: 'Device Information', icon: 'mobile', css_class: 'col-sm-12' }
                    - { property: 'brand' }
                    - { property: 'name' }

                    - { type: 'group', label: 'Web Page', icon: 'external-link', css_class: 'col-sm-12' }
                    - { property: 'webPage', type: 'url' }
