easy_admin:
    entities:
        Repair:
            class: AppBundle\Entity\Repair
            password_encoding: { algorithm: 'bcrypt', cost: 4 }
            list:
                title: 'Reparaciones'
                sort: 'startDate'
                fields: [ 'code', 'client', 'repairAssigned', 'device', { property: 'state.nameAndColor', template: 'state.html.twig', label: 'State' }, 'description', 'cost', 'advance', 'discount', 'startDate', 'deliveryDate' ]
            show:
                fields: [ 'id', 'code', 'client', 'repairAssigned', 'device', 'device.imeiPrimary', 'device.imeiSecondary', { property: 'state.nameAndColor', template: 'state.html.twig', label: 'State' }, 'description', 'cost', 'advance', 'discount', 'startDate', 'deliveryDate' ]
            form:
                fields:
                    - { type: 'group', label: 'Code', icon: 'barcode', css_class: 'col-sm-6' }
                    - { property: 'code', help: 'Código alfanumérico de 15 dígitos max., si no se especifica es auto generado', css_class: 'large', type_options: { required: false } }

                    - { type: 'group', label: 'Repair info', icon: 'cogs', css_class: 'col-sm-6' }
                    - { property: 'client', label: 'Dueño' }
                    - { property: 'repairAssigned' }
                    - { type: 'divider' }

                    - { type: 'group', label: 'Device info', icon: 'mobile', css_class: 'col-sm-6' }
                    - { property: 'device' }
                    - { property: 'description', type: 'ckeditor' }
                    - { property: 'state' }
                    - { type: 'divider' }

                    - { type: 'group', label: 'Cost', icon: 'credit-card', css_class: 'col-sm-6' }
                    - { property: 'cost', type: 'money', type_options: { currency: 'EUR' } }
                    - { property: 'advance', type: 'money', type_options: { currency: 'EUR' } }
                    - { property: 'discount', type: 'money', type_options: { currency: 'EUR' } }

                    - { type: 'group', label: 'Fecha', icon: 'calendar', css_class: 'col-sm-6' }
                    - { property: 'startDate', help: 'Guarda la fecha actual si no se especifica alguna', type_options: { required: false } }
                    - { property: 'deliveryDate' }
